name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:13
        env:
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install backend deps
        run: |
          cd backend
          pip install -r requirements.txt
      - name: Lint Python
        run: |
          cd backend
          flake8 .
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install frontend deps
        run: |
          cd frontend
          npm ci
      - name: Lint JS
        run: |
          cd frontend
          npm run lint || echo "Add lint config if desired"
